// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBF6qsnU-AarmM7enkrubAoerWEATJhk',
    appId: '1:179974387519:web:0c60da8a46a532ffac458a',
    messagingSenderId: '179974387519',
    projectId: 'bmi-v1-f4504',
    authDomain: 'bmi-v1-f4504.firebaseapp.com',
    storageBucket: 'bmi-v1-f4504.appspot.com',
    measurementId: 'G-8S41EKCVBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYuxXVChKVPVyGw0vJj2bJzQCwg61qE4k',
    appId: '1:179974387519:android:cf1df4b1ff5b253fac458a',
    messagingSenderId: '179974387519',
    projectId: 'bmi-v1-f4504',
    storageBucket: 'bmi-v1-f4504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpj4u2XTQGK_3geH1hAUOIPqe_7ECv4uU',
    appId: '1:179974387519:ios:9955ccac021b3362ac458a',
    messagingSenderId: '179974387519',
    projectId: 'bmi-v1-f4504',
    storageBucket: 'bmi-v1-f4504.appspot.com',
    iosClientId: '179974387519-hkit5m4k14uhpsijflau1lvako7hoa4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmi',
  );
}
